### ISSUE TITLE
Cannot mix bigint error

### ISSUE THREAD

**Issue by SomeAspy** [Puyodead1/powercord-ownertag#17]
`Failed to run injection "ownertag-members" TypeError: Cannot mix BigInt and other types, use explicit conversions
    at getPermissionsRaw (C:\Users\aiden\powercord\src\Powercord\plugins\powercord-ownertag\index.js:61:49)
    at t.<anonymous> (C:\Users\aiden\powercord\src\Powercord\plugins\powercord-ownertag\index.js:382:41)
    at C:\Users\aiden\powercord\src\fake_node_modules\powercord\injector\index.js:104:32
    at Array.forEach (<anonymous>)
    at Object._runInjections (C:\Users\aiden\powercord\src\fake_node_modules\powercord\injector\index.js:102:16)
    at t.renderDecorators (C:\Users\aiden\powercord\src\fake_node_modules\powercord\injector\index.js:37:27)
_error @ VM876 C:\Users\aiden\powercord\src\fake_node_modules\powercord\injector\index.js:113
`

**Comment by Puyodead1** [comment]
This should be fixed in the latest commit
